name: Build the flutter version of the RustDesk

on:
  workflow_dispatch:
    inputs:
      rename:
        description: 'Application Name (e.g., FUSION REMOTE)'
        required: true
        default: 'FUSION REMOTE'
      key:
        description: 'Your Public Key'
        required: true
      host:
        description: 'Your Host (e.g., fusion-cloud-remote.ddns.net)'
        required: true
        default: 'fusion-cloud-remote.ddns.net'

env:
  RUSTDESK_NAME: ${{ github.event.inputs.rename }}
  RUSTDESK_ID_SERVER: ${{ github.event.inputs.host }}
  RUSTDESK_RELAY_SERVER: ${{ github.event.inputs.host }}
  RUSTDESK_KEY: ${{ github.event.inputs.key }}
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  SCITER_RUST_VERSION: "1.75"

jobs:
  build-windows:
    name: build-windows-x64-custom
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false
      - name: Install vcpkg dependencies
        run: |
          vcpkg install --triplet x64-windows-static --x-install-root="C:\vcpkg\installed"
        shell: bash
      - name: Build rustdesk
        run: |
          python3 .\build.py --portable --flutter --skip-portable-pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FUSION-REMOTE-windows
          path: flutter/build/windows/x64/runner/Release/
